### PR TITLE
Update enable motors commands

### LINKED ISSUE #137: AxiDraw V3 draws at half size
Using the default axidraw.ini configuration, the AxiDraw V3 draws at half the expected size. Ie., instructing the pen to move to `{x: 100, y: 100}`, only moves the pen along half the range of each axis.

I have two potential fixes, but I want to check which approach is preferable before opening a PR.

One approach is to add a new axidraw_v3.ini configuration, as I've done in my [fork](https://github.com/techninja/cncserver/compare/master...bryangale:cncserver:master), and had been about to open a PR for.

The other is to make a two-character change in the existing axidraw.ini - `enablemotors = "EM,%p"` to `enablemotors = "EM,%p,1"`. It appears without this second parameter (which is [required in the latest firmware](https://evil-mad.github.io/EggBot/ebb.html#EM)), the command is ignored by the V3, so it remains in the firmware's default 1/16 precision mode, rather than the 1/8 precision the `maxArea` width/height is set for, giving the half size drawing behaviour.

However, I don't have access to V2 hardware to check this isn't a breaking change.

In any case, there does appear to be an issue in the axidraw.ini (and axidraw_v3a3.ini) configurations, in that the one-parameter `enablemotors` command matches the legacy firmware, but the comment (that precision is a value from 1-5, rather than 1-4) matches the current firmware.

### PR DESCRIPTION
**Pull request by ghost**
This PR updates the `enablemotors` commands in each machine configuration, to avoid a reliance on how the EiBotBoard firmware handles a missing second parameter, which varies across firmware versions. This fixes #137.

### CODE REVIEW

**Comment by oskay** [comment]
Looks good to me!

**Comment by bryangale** [comment]
@oskay What's the process for getting this merged in? Anyone I should be tagging here? I don't have the necessary permissions to merge it myself

**Comment by oskay** [comment]
@techninja I don't see any issues here. Any objection to merging this?

**Comment by techninja** [comment]
I wonder if @dtgreene has a free minute to take a look, I haven't had a moment. We'd probably also want to run another release

**Comment by dtgreene** [comment]
@techninja Looks good to me! I can merge and create a new release

**Pull request merged**
