### PR TITLE
Fix issues with string vs float type

### PR DESCRIPTION
**Pull request by docprofsky**
Fix problems with the speeds from the config file being strings.

### CODE REVIEW

**Comment by techninja** [comment]
Do you actually test these things? yea! Sheesh. Everything from the config comes in as strings because it's parsed directly from the text INI files. Just turn these into converted variables then do the math on them, will work faster and look cleaner, even if it is a few more lines.

When/If this ever becomes something else, conversion won't be needed, but right now, you should likely be doing a conversion to a number type with ANY concatenation or math. Actually makes it faster anyways.

**Comment by techninja** [comment]
That should also help immediately below for this line: https://github.com/techninja/cncserver/blob/master/cncserver.js#L1561

**Comment by docprofsky** [comment]
WIth the string fixing the bounding works as expected.

**Comment by docprofsky** [comment]
This should be good.

**Comment by techninja** [comment]
Alright, alright, You've done what I've asked. Thank you. Here's your gold star :star2:  :)

**Pull request merged**
